// Code generated by Microsoft (R) AutoRest Code Generator 0.9.7.0
// Changes may cause incorrect behavior and will be lost if the code is regenerated.

using System;
using System.Linq;
using Newtonsoft.Json.Linq;

namespace Pltkw3msUI1.Models
{
    public partial class Address
    {
        private string _city;
        
        /// <summary>
        /// Optional.
        /// </summary>
        public string City
        {
            get { return this._city; }
            set { this._city = value; }
        }
        
        private string _houseNo;
        
        /// <summary>
        /// Optional.
        /// </summary>
        public string HouseNo
        {
            get { return this._houseNo; }
            set { this._houseNo = value; }
        }
        
        private string _postalCode;
        
        /// <summary>
        /// Optional.
        /// </summary>
        public string PostalCode
        {
            get { return this._postalCode; }
            set { this._postalCode = value; }
        }
        
        private string _street;
        
        /// <summary>
        /// Optional.
        /// </summary>
        public string Street
        {
            get { return this._street; }
            set { this._street = value; }
        }
        
        /// <summary>
        /// Initializes a new instance of the Address class.
        /// </summary>
        public Address()
        {
        }
        
        /// <summary>
        /// Serialize the object
        /// </summary>
        /// <returns>
        /// Returns the json model for the type Address
        /// </returns>
        public virtual JToken SerializeJson(JToken outputObject)
        {
            if (outputObject == null)
            {
                outputObject = new JObject();
            }
            if (this.City != null)
            {
                outputObject["City"] = this.City;
            }
            if (this.HouseNo != null)
            {
                outputObject["HouseNo"] = this.HouseNo;
            }
            if (this.PostalCode != null)
            {
                outputObject["PostalCode"] = this.PostalCode;
            }
            if (this.Street != null)
            {
                outputObject["Street"] = this.Street;
            }
            return outputObject;
        }
        
        /// <summary>
        /// Deserialize the object
        /// </summary>
        public virtual void DeserializeJson(JToken inputObject)
        {
            if (inputObject != null && inputObject.Type != JTokenType.Null)
            {
                JToken cityValue = inputObject["City"];
                if (cityValue != null && cityValue.Type != JTokenType.Null)
                {
                    this.City = ((string)cityValue);
                }
                JToken houseNoValue = inputObject["HouseNo"];
                if (houseNoValue != null && houseNoValue.Type != JTokenType.Null)
                {
                    this.HouseNo = ((string)houseNoValue);
                }
                JToken postalCodeValue = inputObject["PostalCode"];
                if (postalCodeValue != null && postalCodeValue.Type != JTokenType.Null)
                {
                    this.PostalCode = ((string)postalCodeValue);
                }
                JToken streetValue = inputObject["Street"];
                if (streetValue != null && streetValue.Type != JTokenType.Null)
                {
                    this.Street = ((string)streetValue);
                }
            }
        }
    }
}
