// Code generated by Microsoft (R) AutoRest Code Generator 0.9.7.0
// Changes may cause incorrect behavior and will be lost if the code is regenerated.

using System;
using System.Collections.Generic;
using System.Linq;
using Newtonsoft.Json.Linq;
using Pltkw3msUI1.Models;

namespace Pltkw3msUI1.Models
{
    public static partial class CustomerCollection
    {
        /// <summary>
        /// Serialize the object
        /// </summary>
        /// <returns>
        /// Returns the json model for the type IList
        /// </returns>
        public static JToken SerializeJson(IList<Customer> value, JToken outputObject)
        {
            if (outputObject == null)
            {
                outputObject = new JObject();
            }
            JArray iListSequence = null;
            if (value != null)
            {
                iListSequence = new JArray();
                outputObject = iListSequence;
                foreach (Customer iListItem in value)
                {
                    if (iListItem != null)
                    {
                        iListSequence.Add(iListItem.SerializeJson(null));
                    }
                }
            }
            return outputObject;
        }
        
        /// <summary>
        /// Deserialize the object
        /// </summary>
        public static IList<Customer> DeserializeJson(JToken inputObject)
        {
            IList<Customer> deserializedObject = new List<Customer>();
            foreach (JToken iListValue in ((JArray)inputObject))
            {
                Customer customer = new Customer();
                customer.DeserializeJson(iListValue);
                deserializedObject.Add(customer);
            }
            return deserializedObject;
        }
    }
}
