// Code generated by Microsoft (R) AutoRest Code Generator 0.9.7.0
// Changes may cause incorrect behavior and will be lost if the code is regenerated.

using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading;
using System.Threading.Tasks;
using Microsoft.Rest;
using Pltkw3msUI1;
using Pltkw3msUI1.Models;

namespace Pltkw3msUI1
{
    public static partial class CustomerOperationsExtensions
    {
        /// <param name='operations'>
        /// Reference to the Pltkw3msUI1.ICustomerOperations.
        /// </param>
        /// <param name='value'>
        /// Required.
        /// </param>
        public static object AddManyCustomersByValue(this ICustomerOperations operations, IList<Customer> value)
        {
            return Task.Factory.StartNew((object s) => 
            {
                return ((ICustomerOperations)s).AddManyCustomersByValueAsync(value);
            }
            , operations, CancellationToken.None, TaskCreationOptions.None, TaskScheduler.Default).Unwrap().GetAwaiter().GetResult();
        }
        
        /// <param name='operations'>
        /// Reference to the Pltkw3msUI1.ICustomerOperations.
        /// </param>
        /// <param name='value'>
        /// Required.
        /// </param>
        /// <param name='cancellationToken'>
        /// Cancellation token.
        /// </param>
        public static async Task<object> AddManyCustomersByValueAsync(this ICustomerOperations operations, IList<Customer> value, CancellationToken cancellationToken = default(System.Threading.CancellationToken))
        {
            Microsoft.Rest.HttpOperationResponse<object> result = await operations.AddManyCustomersByValueWithOperationResponseAsync(value, cancellationToken).ConfigureAwait(false);
            return result.Body;
        }
        
        /// <param name='operations'>
        /// Reference to the Pltkw3msUI1.ICustomerOperations.
        /// </param>
        /// <param name='id'>
        /// Required.
        /// </param>
        public static object DeleteById(this ICustomerOperations operations, int id)
        {
            return Task.Factory.StartNew((object s) => 
            {
                return ((ICustomerOperations)s).DeleteByIdAsync(id);
            }
            , operations, CancellationToken.None, TaskCreationOptions.None, TaskScheduler.Default).Unwrap().GetAwaiter().GetResult();
        }
        
        /// <param name='operations'>
        /// Reference to the Pltkw3msUI1.ICustomerOperations.
        /// </param>
        /// <param name='id'>
        /// Required.
        /// </param>
        /// <param name='cancellationToken'>
        /// Cancellation token.
        /// </param>
        public static async Task<object> DeleteByIdAsync(this ICustomerOperations operations, int id, CancellationToken cancellationToken = default(System.Threading.CancellationToken))
        {
            Microsoft.Rest.HttpOperationResponse<object> result = await operations.DeleteByIdWithOperationResponseAsync(id, cancellationToken).ConfigureAwait(false);
            return result.Body;
        }
        
        /// <param name='operations'>
        /// Reference to the Pltkw3msUI1.ICustomerOperations.
        /// </param>
        public static IList<Customer> Get(this ICustomerOperations operations)
        {
            return Task.Factory.StartNew((object s) => 
            {
                return ((ICustomerOperations)s).GetAsync();
            }
            , operations, CancellationToken.None, TaskCreationOptions.None, TaskScheduler.Default).Unwrap().GetAwaiter().GetResult();
        }
        
        /// <param name='operations'>
        /// Reference to the Pltkw3msUI1.ICustomerOperations.
        /// </param>
        /// <param name='cancellationToken'>
        /// Cancellation token.
        /// </param>
        public static async Task<IList<Customer>> GetAsync(this ICustomerOperations operations, CancellationToken cancellationToken = default(System.Threading.CancellationToken))
        {
            Microsoft.Rest.HttpOperationResponse<System.Collections.Generic.IList<Pltkw3msUI1.Models.Customer>> result = await operations.GetWithOperationResponseAsync(cancellationToken).ConfigureAwait(false);
            return result.Body;
        }
        
        /// <param name='operations'>
        /// Reference to the Pltkw3msUI1.ICustomerOperations.
        /// </param>
        /// <param name='id'>
        /// Required. ID Customer
        /// </param>
        public static Customer GetById(this ICustomerOperations operations, int id)
        {
            return Task.Factory.StartNew((object s) => 
            {
                return ((ICustomerOperations)s).GetByIdAsync(id);
            }
            , operations, CancellationToken.None, TaskCreationOptions.None, TaskScheduler.Default).Unwrap().GetAwaiter().GetResult();
        }
        
        /// <param name='operations'>
        /// Reference to the Pltkw3msUI1.ICustomerOperations.
        /// </param>
        /// <param name='id'>
        /// Required. ID Customer
        /// </param>
        /// <param name='cancellationToken'>
        /// Cancellation token.
        /// </param>
        public static async Task<Customer> GetByIdAsync(this ICustomerOperations operations, int id, CancellationToken cancellationToken = default(System.Threading.CancellationToken))
        {
            Microsoft.Rest.HttpOperationResponse<Pltkw3msUI1.Models.Customer> result = await operations.GetByIdWithOperationResponseAsync(id, cancellationToken).ConfigureAwait(false);
            return result.Body;
        }
        
        /// <param name='operations'>
        /// Reference to the Pltkw3msUI1.ICustomerOperations.
        /// </param>
        /// <param name='start'>
        /// Required.
        /// </param>
        public static IList<Customer> GetPageByStart(this ICustomerOperations operations, int start)
        {
            return Task.Factory.StartNew((object s) => 
            {
                return ((ICustomerOperations)s).GetPageByStartAsync(start);
            }
            , operations, CancellationToken.None, TaskCreationOptions.None, TaskScheduler.Default).Unwrap().GetAwaiter().GetResult();
        }
        
        /// <param name='operations'>
        /// Reference to the Pltkw3msUI1.ICustomerOperations.
        /// </param>
        /// <param name='start'>
        /// Required.
        /// </param>
        /// <param name='cancellationToken'>
        /// Cancellation token.
        /// </param>
        public static async Task<IList<Customer>> GetPageByStartAsync(this ICustomerOperations operations, int start, CancellationToken cancellationToken = default(System.Threading.CancellationToken))
        {
            Microsoft.Rest.HttpOperationResponse<System.Collections.Generic.IList<Pltkw3msUI1.Models.Customer>> result = await operations.GetPageByStartWithOperationResponseAsync(start, cancellationToken).ConfigureAwait(false);
            return result.Body;
        }
        
        /// <param name='operations'>
        /// Reference to the Pltkw3msUI1.ICustomerOperations.
        /// </param>
        /// <param name='value'>
        /// Required.
        /// </param>
        public static object PostByValue(this ICustomerOperations operations, Customer value)
        {
            return Task.Factory.StartNew((object s) => 
            {
                return ((ICustomerOperations)s).PostByValueAsync(value);
            }
            , operations, CancellationToken.None, TaskCreationOptions.None, TaskScheduler.Default).Unwrap().GetAwaiter().GetResult();
        }
        
        /// <param name='operations'>
        /// Reference to the Pltkw3msUI1.ICustomerOperations.
        /// </param>
        /// <param name='value'>
        /// Required.
        /// </param>
        /// <param name='cancellationToken'>
        /// Cancellation token.
        /// </param>
        public static async Task<object> PostByValueAsync(this ICustomerOperations operations, Customer value, CancellationToken cancellationToken = default(System.Threading.CancellationToken))
        {
            Microsoft.Rest.HttpOperationResponse<object> result = await operations.PostByValueWithOperationResponseAsync(value, cancellationToken).ConfigureAwait(false);
            return result.Body;
        }
        
        /// <param name='operations'>
        /// Reference to the Pltkw3msUI1.ICustomerOperations.
        /// </param>
        /// <param name='id'>
        /// Required.
        /// </param>
        /// <param name='value'>
        /// Required.
        /// </param>
        public static object PutByIdAndValue(this ICustomerOperations operations, int id, string value)
        {
            return Task.Factory.StartNew((object s) => 
            {
                return ((ICustomerOperations)s).PutByIdAndValueAsync(id, value);
            }
            , operations, CancellationToken.None, TaskCreationOptions.None, TaskScheduler.Default).Unwrap().GetAwaiter().GetResult();
        }
        
        /// <param name='operations'>
        /// Reference to the Pltkw3msUI1.ICustomerOperations.
        /// </param>
        /// <param name='id'>
        /// Required.
        /// </param>
        /// <param name='value'>
        /// Required.
        /// </param>
        /// <param name='cancellationToken'>
        /// Cancellation token.
        /// </param>
        public static async Task<object> PutByIdAndValueAsync(this ICustomerOperations operations, int id, string value, CancellationToken cancellationToken = default(System.Threading.CancellationToken))
        {
            Microsoft.Rest.HttpOperationResponse<object> result = await operations.PutByIdAndValueWithOperationResponseAsync(id, value, cancellationToken).ConfigureAwait(false);
            return result.Body;
        }
    }
}
