// Code generated by Microsoft (R) AutoRest Code Generator 0.9.7.0
// Changes may cause incorrect behavior and will be lost if the code is regenerated.

using System;
using System.Linq;
using System.Threading;
using System.Threading.Tasks;
using Microsoft.Rest;
using Pltkw3msApiUI2.ApiPayment;

namespace Pltkw3msApiUI2.ApiPayment
{
    public static partial class PaymentStatusExtensions
    {
        /// <param name='operations'>
        /// Reference to the Pltkw3msApiUI2.ApiPayment.IPaymentStatus.
        /// </param>
        /// <param name='orderId'>
        /// Required.
        /// </param>
        public static string GetPaymentStatusByOrderid(this IPaymentStatus operations, string orderId)
        {
            return Task.Factory.StartNew((object s) => 
            {
                return ((IPaymentStatus)s).GetPaymentStatusByOrderidAsync(orderId);
            }
            , operations, CancellationToken.None, TaskCreationOptions.None, TaskScheduler.Default).Unwrap().GetAwaiter().GetResult();
        }
        
        /// <param name='operations'>
        /// Reference to the Pltkw3msApiUI2.ApiPayment.IPaymentStatus.
        /// </param>
        /// <param name='orderId'>
        /// Required.
        /// </param>
        /// <param name='cancellationToken'>
        /// Cancellation token.
        /// </param>
        public static async Task<string> GetPaymentStatusByOrderidAsync(this IPaymentStatus operations, string orderId, CancellationToken cancellationToken = default(System.Threading.CancellationToken))
        {
            Microsoft.Rest.HttpOperationResponse<string> result = await operations.GetPaymentStatusByOrderidWithOperationResponseAsync(orderId, cancellationToken).ConfigureAwait(false);
            return result.Body;
        }
    }
}
