// Code generated by Microsoft (R) AutoRest Code Generator 0.9.7.0
// Changes may cause incorrect behavior and will be lost if the code is regenerated.

using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading;
using System.Threading.Tasks;
using Microsoft.Rest;
using Pltkw3msApiUI2.ApiPayment;
using Pltkw3msApiUI2.ApiPayment.Models;

namespace Pltkw3msApiUI2.ApiPayment
{
    public static partial class PaymentExtensions
    {
        /// <param name='operations'>
        /// Reference to the Pltkw3msApiUI2.ApiPayment.IPayment.
        /// </param>
        /// <param name='id'>
        /// Required.
        /// </param>
        public static object DeleteById(this IPayment operations, int id)
        {
            return Task.Factory.StartNew((object s) => 
            {
                return ((IPayment)s).DeleteByIdAsync(id);
            }
            , operations, CancellationToken.None, TaskCreationOptions.None, TaskScheduler.Default).Unwrap().GetAwaiter().GetResult();
        }
        
        /// <param name='operations'>
        /// Reference to the Pltkw3msApiUI2.ApiPayment.IPayment.
        /// </param>
        /// <param name='id'>
        /// Required.
        /// </param>
        /// <param name='cancellationToken'>
        /// Cancellation token.
        /// </param>
        public static async Task<object> DeleteByIdAsync(this IPayment operations, int id, CancellationToken cancellationToken = default(System.Threading.CancellationToken))
        {
            Microsoft.Rest.HttpOperationResponse<object> result = await operations.DeleteByIdWithOperationResponseAsync(id, cancellationToken).ConfigureAwait(false);
            return result.Body;
        }
        
        /// <param name='operations'>
        /// Reference to the Pltkw3msApiUI2.ApiPayment.IPayment.
        /// </param>
        public static IList<string> Get(this IPayment operations)
        {
            return Task.Factory.StartNew((object s) => 
            {
                return ((IPayment)s).GetAsync();
            }
            , operations, CancellationToken.None, TaskCreationOptions.None, TaskScheduler.Default).Unwrap().GetAwaiter().GetResult();
        }
        
        /// <param name='operations'>
        /// Reference to the Pltkw3msApiUI2.ApiPayment.IPayment.
        /// </param>
        /// <param name='cancellationToken'>
        /// Cancellation token.
        /// </param>
        public static async Task<IList<string>> GetAsync(this IPayment operations, CancellationToken cancellationToken = default(System.Threading.CancellationToken))
        {
            Microsoft.Rest.HttpOperationResponse<System.Collections.Generic.IList<string>> result = await operations.GetWithOperationResponseAsync(cancellationToken).ConfigureAwait(false);
            return result.Body;
        }
        
        /// <param name='operations'>
        /// Reference to the Pltkw3msApiUI2.ApiPayment.IPayment.
        /// </param>
        /// <param name='id'>
        /// Required.
        /// </param>
        public static string GetById(this IPayment operations, int id)
        {
            return Task.Factory.StartNew((object s) => 
            {
                return ((IPayment)s).GetByIdAsync(id);
            }
            , operations, CancellationToken.None, TaskCreationOptions.None, TaskScheduler.Default).Unwrap().GetAwaiter().GetResult();
        }
        
        /// <param name='operations'>
        /// Reference to the Pltkw3msApiUI2.ApiPayment.IPayment.
        /// </param>
        /// <param name='id'>
        /// Required.
        /// </param>
        /// <param name='cancellationToken'>
        /// Cancellation token.
        /// </param>
        public static async Task<string> GetByIdAsync(this IPayment operations, int id, CancellationToken cancellationToken = default(System.Threading.CancellationToken))
        {
            Microsoft.Rest.HttpOperationResponse<string> result = await operations.GetByIdWithOperationResponseAsync(id, cancellationToken).ConfigureAwait(false);
            return result.Body;
        }
        
        /// <param name='operations'>
        /// Reference to the Pltkw3msApiUI2.ApiPayment.IPayment.
        /// </param>
        /// <param name='triggerState'>
        /// Required.
        /// </param>
        /// <param name='probability'>
        /// Required.
        /// </param>
        public static PaymentConfirmation PaidInFullPollTriggerByTriggerstateAndProbability(this IPayment operations, string triggerState, double probability)
        {
            return Task.Factory.StartNew((object s) => 
            {
                return ((IPayment)s).PaidInFullPollTriggerByTriggerstateAndProbabilityAsync(triggerState, probability);
            }
            , operations, CancellationToken.None, TaskCreationOptions.None, TaskScheduler.Default).Unwrap().GetAwaiter().GetResult();
        }
        
        /// <param name='operations'>
        /// Reference to the Pltkw3msApiUI2.ApiPayment.IPayment.
        /// </param>
        /// <param name='triggerState'>
        /// Required.
        /// </param>
        /// <param name='probability'>
        /// Required.
        /// </param>
        /// <param name='cancellationToken'>
        /// Cancellation token.
        /// </param>
        public static async Task<PaymentConfirmation> PaidInFullPollTriggerByTriggerstateAndProbabilityAsync(this IPayment operations, string triggerState, double probability, CancellationToken cancellationToken = default(System.Threading.CancellationToken))
        {
            Microsoft.Rest.HttpOperationResponse<Pltkw3msApiUI2.ApiPayment.Models.PaymentConfirmation> result = await operations.PaidInFullPollTriggerByTriggerstateAndProbabilityWithOperationResponseAsync(triggerState, probability, cancellationToken).ConfigureAwait(false);
            return result.Body;
        }
        
        /// <param name='operations'>
        /// Reference to the Pltkw3msApiUI2.ApiPayment.IPayment.
        /// </param>
        /// <param name='value'>
        /// Required.
        /// </param>
        public static object PostByValue(this IPayment operations, string value)
        {
            return Task.Factory.StartNew((object s) => 
            {
                return ((IPayment)s).PostByValueAsync(value);
            }
            , operations, CancellationToken.None, TaskCreationOptions.None, TaskScheduler.Default).Unwrap().GetAwaiter().GetResult();
        }
        
        /// <param name='operations'>
        /// Reference to the Pltkw3msApiUI2.ApiPayment.IPayment.
        /// </param>
        /// <param name='value'>
        /// Required.
        /// </param>
        /// <param name='cancellationToken'>
        /// Cancellation token.
        /// </param>
        public static async Task<object> PostByValueAsync(this IPayment operations, string value, CancellationToken cancellationToken = default(System.Threading.CancellationToken))
        {
            Microsoft.Rest.HttpOperationResponse<object> result = await operations.PostByValueWithOperationResponseAsync(value, cancellationToken).ConfigureAwait(false);
            return result.Body;
        }
        
        /// <param name='operations'>
        /// Reference to the Pltkw3msApiUI2.ApiPayment.IPayment.
        /// </param>
        /// <param name='id'>
        /// Required.
        /// </param>
        /// <param name='value'>
        /// Required.
        /// </param>
        public static object PutByIdAndValue(this IPayment operations, int id, string value)
        {
            return Task.Factory.StartNew((object s) => 
            {
                return ((IPayment)s).PutByIdAndValueAsync(id, value);
            }
            , operations, CancellationToken.None, TaskCreationOptions.None, TaskScheduler.Default).Unwrap().GetAwaiter().GetResult();
        }
        
        /// <param name='operations'>
        /// Reference to the Pltkw3msApiUI2.ApiPayment.IPayment.
        /// </param>
        /// <param name='id'>
        /// Required.
        /// </param>
        /// <param name='value'>
        /// Required.
        /// </param>
        /// <param name='cancellationToken'>
        /// Cancellation token.
        /// </param>
        public static async Task<object> PutByIdAndValueAsync(this IPayment operations, int id, string value, CancellationToken cancellationToken = default(System.Threading.CancellationToken))
        {
            Microsoft.Rest.HttpOperationResponse<object> result = await operations.PutByIdAndValueWithOperationResponseAsync(id, value, cancellationToken).ConfigureAwait(false);
            return result.Body;
        }
        
        /// <param name='operations'>
        /// Reference to the Pltkw3msApiUI2.ApiPayment.IPayment.
        /// </param>
        /// <param name='triggerState'>
        /// Required.
        /// </param>
        /// <param name='searchPattern'>
        /// Optional.
        /// </param>
        public static string TouchedFilesPollTriggerByTriggerstateAndSearchpattern(this IPayment operations, string triggerState, string searchPattern = null)
        {
            return Task.Factory.StartNew((object s) => 
            {
                return ((IPayment)s).TouchedFilesPollTriggerByTriggerstateAndSearchpatternAsync(triggerState, searchPattern);
            }
            , operations, CancellationToken.None, TaskCreationOptions.None, TaskScheduler.Default).Unwrap().GetAwaiter().GetResult();
        }
        
        /// <param name='operations'>
        /// Reference to the Pltkw3msApiUI2.ApiPayment.IPayment.
        /// </param>
        /// <param name='triggerState'>
        /// Required.
        /// </param>
        /// <param name='searchPattern'>
        /// Optional.
        /// </param>
        /// <param name='cancellationToken'>
        /// Cancellation token.
        /// </param>
        public static async Task<string> TouchedFilesPollTriggerByTriggerstateAndSearchpatternAsync(this IPayment operations, string triggerState, string searchPattern = null, CancellationToken cancellationToken = default(System.Threading.CancellationToken))
        {
            Microsoft.Rest.HttpOperationResponse<string> result = await operations.TouchedFilesPollTriggerByTriggerstateAndSearchpatternWithOperationResponseAsync(triggerState, searchPattern, cancellationToken).ConfigureAwait(false);
            return result.Body;
        }
    }
}
