// Code generated by Microsoft (R) AutoRest Code Generator 0.9.7.0
// Changes may cause incorrect behavior and will be lost if the code is regenerated.

using System;
using System.Linq;
using Newtonsoft.Json.Linq;

namespace Pltkw3msApiUI2.ApiPayment.Models
{
    public partial class PaymentConfirmation
    {
        private int? _orderId;
        
        /// <summary>
        /// Optional.
        /// </summary>
        public int? OrderId
        {
            get { return this._orderId; }
            set { this._orderId = value; }
        }
        
        private DateTimeOffset? _paymentDate;
        
        /// <summary>
        /// Optional.
        /// </summary>
        public DateTimeOffset? PaymentDate
        {
            get { return this._paymentDate; }
            set { this._paymentDate = value; }
        }
        
        private string _paymentType;
        
        /// <summary>
        /// Optional.
        /// </summary>
        public string PaymentType
        {
            get { return this._paymentType; }
            set { this._paymentType = value; }
        }
        
        /// <summary>
        /// Initializes a new instance of the PaymentConfirmation class.
        /// </summary>
        public PaymentConfirmation()
        {
        }
        
        /// <summary>
        /// Deserialize the object
        /// </summary>
        public virtual void DeserializeJson(JToken inputObject)
        {
            if (inputObject != null && inputObject.Type != JTokenType.Null)
            {
                JToken orderIdValue = inputObject["OrderId"];
                if (orderIdValue != null && orderIdValue.Type != JTokenType.Null)
                {
                    this.OrderId = ((int)orderIdValue);
                }
                JToken paymentDateValue = inputObject["PaymentDate"];
                if (paymentDateValue != null && paymentDateValue.Type != JTokenType.Null)
                {
                    this.PaymentDate = ((DateTimeOffset)paymentDateValue);
                }
                JToken paymentTypeValue = inputObject["PaymentType"];
                if (paymentTypeValue != null && paymentTypeValue.Type != JTokenType.Null)
                {
                    this.PaymentType = ((string)paymentTypeValue);
                }
            }
        }
    }
}
